name: DoSell
favicon: null
layout_spectrum: 0.54423
typography_spectrum: 0.56769
title: 'DoSell Blog: Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f10801'
    - '#000000'
    - '#c3c3c3'
    - '#7e7e7e'
  brandStrength: 0.4375
  lightness: 0.875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
