name: DoSell
favicon: null
layout_spectrum: 0.42746
typography_spectrum: 0.666385
title: 'News, Trends, Insights of Business Architecture, Industrial Design, Engineering & Innovation ...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
