analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0C8B8'
    - '#000000'
    - '#888080'
    - '#000000'
    - '#000000'
  brandStrength: 0.5
  lightness: 1
  rhythmicContrast: 0.5
  saturation: 0.8125
cta: {}
layout_spectrum: 0.226351
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.32219
