name: DoSell
favicon: null
layout_spectrum: 0.47372
typography_spectrum: 0.666385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f7f8e'
    - '#2e2b26'
    - '#d9d9d9'
    - '#020202'
    - '#ba957b'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
