name: DoSell
favicon: null
layout_spectrum: 0.95036
typography_spectrum: 0.45939
title: DoSell Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bfbfbf'
    - '#b61a01'
    - '#636363'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
