name: DoSell
favicon: null
layout_spectrum: 0.02798
typography_spectrum: 0.45577
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2d2c'
    - '#ffffff'
    - '#ee382b'
    - '#8d8f8e'
    - '#92322c'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
