name: DoSell
favicon: null
layout_spectrum: 0.49285
typography_spectrum: 0.33974
title: 'DoSell: News, Trends, Insights of Product Design _ Engineering _ Business Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f7f8e'
    - '#2e2b26'
    - '#d9d9d9'
    - '#020202'
    - '#ba957b'
  brandStrength: 0.8125
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
