analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#000000'
    - '#58534f'
    - '#d8d8d8'
    - '#b4a898'
    - '#f7131d'
  brandStrength: 0.875
  lightness: 0.9375
  rhythmicContrast: 0.701858
  saturation: 0.6875
cta: {}
layout_spectrum: 0.371622
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
