name: 'DoSell Blog '
favicon: null
layout_spectrum: 0.98089
typography_spectrum: 0.32219
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#727e8a'
    - '#1d2025'
    - '#c0c0c0'
    - '#3c4b60'
  brandStrength: 0.5625
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
