layout_spectrum: 0.07830087724141777
typography_spectrum: 0.6617070229258388
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.4254384932573885
  lightness: 0.6903104947414249
  saturation: 0.3633734395261854
  rhythmicContrast: 0.8015583164524287
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
name: 'DoSell Open Innovation Blog '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: null
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
description: Open Innovation
purpose: []
