analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#808078'
    - '#000000'
    - '#000000'
  brandStrength: 0.763514
  lightness: 0.921453
  rhythmicContrast: 0.616554
  saturation: 0.750845
cta: {}
layout_spectrum: 0.52027
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
