name: DoSell
favicon: null
layout_spectrum: 0.8944
typography_spectrum: 0.45577
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2e1e7'
    - '#abcfef'
    - '#81b7db'
    - '#3e3536'
    - '#905566'
  brandStrength: 0.625
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
