layout_spectrum: 0.03893864154815674
typography_spectrum: 0.08928224560804665
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.7142401360906661
  lightness: 0.6527267792262137
  saturation: 0.8322083349339664
  rhythmicContrast: 0.7292862497270107
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
name: 'DoSell Open Innovation Blog '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: null
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
description: Open Innovation
purpose: []
