name: DoSell
favicon: null
layout_spectrum: 0.06588
typography_spectrum: 0.56769
title: 'DoSell Blog: Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d02603'
    - '#ffffff'
    - '#636768'
    - '#84b9e3'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
