analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E8E8E0'
    - '#000000'
    - '#788078'
    - '#000000'
    - '#000000'
  brandStrength: 0.6875
  lightness: 0.75
  rhythmicContrast: 0.25
  saturation: 0.625
cta: {}
layout_spectrum: 0.121622
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.460304
