analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0D0D0'
    - '#000000'
    - '#888880'
    - '#000000'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.5625
  rhythmicContrast: 0.5
  saturation: 0.8125
cta: {}
layout_spectrum: 0.45936
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.666385
