name: DoSell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38934
title: DoSell Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d02603'
    - '#ffffff'
    - '#636768'
    - '#84b9e3'
  brandStrength: 0.625
  lightness: 0.45594477793201804
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
