name: DoSell
favicon: null
layout_spectrum: 0.90343
typography_spectrum: 0.67418
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#775319'
    - '#c39f78'
    - '#f8dcc8'
    - '#97744b'
  brandStrength: 0.125
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
