analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#C0C0C0'
    - '#814404'
    - '#686868'
    - '#F88810'
    - '#000000'
  brandStrength: 0.782095
  lightness: 0.863176
  rhythmicContrast: 0.528716
  saturation: 0.6875
cta: {}
layout_spectrum: 0.412162
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
