analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#A8B8B8'
    - '#282010'
    - '#909080'
    - '#B69249'
    - '#000000'
  brandStrength: 0.763514
  lightness: 0.921453
  rhythmicContrast: 0.616554
  saturation: 0.750845
cta: {}
layout_spectrum: 0.467905
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
