analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#988868'
    - '#000000'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.777027
  rhythmicContrast: 0.5
  saturation: 0.8125
cta: {}
layout_spectrum: 0.125
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.244932
