name: 'DoSell Blog '
favicon: null
layout_spectrum: 0.15154
typography_spectrum: 0.32219
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#58534f'
    - '#d8d8d8'
    - '#b4a898'
    - '#f7131d'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
