name: DoSell
favicon: null
layout_spectrum: 0.24458
typography_spectrum: 0.56769
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2a2a'
    - '#e2e2e2'
    - '#e0382d'
    - '#8f2d2b'
    - '#bdbdbd'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
