analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0D0A8'
    - '#302810'
    - '#A09068'
    - '#BF9F40'
    - '#E8E8C0'
  brandStrength: 0.746622
  lightness: 0.978885
  rhythmicContrast: 0.737331
  saturation: 0.693412
cta: {}
layout_spectrum: 0.513513
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
