analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B8C0B8'
    - '#000000'
    - '#989890'
    - '#000000'
    - '#000000'
  brandStrength: 0.782095
  lightness: 0.863176
  rhythmicContrast: 0.528716
  saturation: 0.6875
cta: {}
layout_spectrum: 0.911318
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
