name: DoSell
favicon: null
layout_spectrum: 0.71571
typography_spectrum: 0.45577
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ba7b3'
    - '#aedcec'
    - '#090909'
    - '#1b7dfc'
  brandStrength: 0.75
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
