analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#185070'
    - '#587890'
    - '#4090B0'
    - '#E8F8F0'
  brandStrength: 0.746622
  lightness: 0.978885
  rhythmicContrast: 0.737331
  saturation: 0.693412
cta: {}
layout_spectrum: 0.538007
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
