name: DoSell
favicon: null
layout_spectrum: 0.05144
typography_spectrum: 0.57491
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6f7f8e'
    - '#2e2b26'
    - '#d9d9d9'
    - '#020202'
    - '#ba957b'
  brandStrength: 0.6875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
