name: DoSell
favicon: null
layout_spectrum: 0.49285
typography_spectrum: 0.33974
title: 'DoSell: News, Trends, Insights of Product Design _ Engineering _ Business Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#52453c'
    - '#9b8d84'
    - '#cd1841'
    - '#00abea'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
