analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#185070'
    - '#587890'
    - '#4090B0'
    - '#E8F8F0'
  brandStrength: 0.849662
  lightness: 0.924831
  rhythmicContrast: 0.63598
  saturation: 0.693412
cta: {}
layout_spectrum: 1
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
