analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B8B8B0'
    - '#000000'
    - '#909088'
    - '#000000'
    - '#000000'
  brandStrength: 0.866554
  lightness: 0.804054
  rhythmicContrast: 0.646959
  saturation: 0.576858
cta: {}
layout_spectrum: 0.467905
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
