name: DoSell
favicon: null
layout_spectrum: 0.95578
typography_spectrum: 0.30235
title: DoSell Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#ffffe5'
    - '#ed352b'
    - '#d6cabe'
    - '#9c9b90'
  brandStrength: 0.5625
  lightness: 0.875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
