name: DoSell
favicon: null
layout_spectrum: 0.97563
typography_spectrum: 0.56769
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#687fa1'
    - '#001032'
    - '#fe635f'
    - '#45fcf1'
  brandStrength: 0.75
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
