name: DoSell
favicon: null
layout_spectrum: 0.39078
typography_spectrum: 0.35569
title: 'DoSell: News, Trends, Insights of Product Design _ Engineering _ Business Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dd3d23'
    - '#2b2a28'
    - '#5c5c5c'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
