name: DoSell
favicon: null
layout_spectrum: 0.46841
typography_spectrum: 0.52246
title: 'News, Trends, Insights of Product Design - Engineering - Business Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dd3d23'
    - '#2b2a28'
    - '#5c5c5c'
  brandStrength: 0.797297
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.712838
purpose: []
