name: 'DoSell Blog '
favicon: null
layout_spectrum: 0.125
typography_spectrum: 0.244932
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#C0C0B0'
    - '#000000'
    - '#988868'
    - '#000000'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.777027
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
