analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B0C0C0'
    - '#3080A0'
    - '#888878'
    - '#40B0D0'
    - '#000000'
  brandStrength: 0.706081
  lightness: 0.893581
  rhythmicContrast: 0.701858
  saturation: 0.624155
cta: {}
layout_spectrum: 0.541385
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
