name: DoSell
favicon: null
layout_spectrum: 0.544764
typography_spectrum: 0.95664
title: DoSell Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2d2c'
    - '#ffffff'
    - '#ee382b'
    - '#8d8f8e'
    - '#92322c'
  brandStrength: 0.75
  lightness: 0.45594477793201804
  saturation: 0.4251121545676142
  rhythmicContrast: 0.5
purpose: []
