name: DoSell
favicon: null
layout_spectrum: 0.39079
typography_spectrum: 0.57491
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dd3d23'
    - '#2b2a28'
    - '#5c5c5c'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
