analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#000000'
    - '#98A098'
    - '#000000'
    - '#000000'
  brandStrength: 0.734797
  lightness: 0.961149
  rhythmicContrast: 0.63598
  saturation: 0.693412
cta: {}
layout_spectrum: 1
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
