analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#dd3d23'
    - '#2b2a28'
    - '#5c5c5c'
  brandStrength: 0.797297
  lightness: 0.649493
  rhythmicContrast: 0.712838
  saturation: 0.234797
cta: {}
layout_spectrum: 0.36402
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.397804
