analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B0B8B0'
    - '#000000'
    - '#889070'
    - '#000000'
    - '#000000'
  brandStrength: 0.734797
  lightness: 0.846284
  rhythmicContrast: 0.63598
  saturation: 0.693412
cta: {}
layout_spectrum: 0.913007
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
