analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D8E0C8'
    - '#602E25'
    - '#485058'
    - '#A85040'
    - '#E8F0F8'
  brandStrength: 0.849662
  lightness: 0.924831
  rhythmicContrast: 0.63598
  saturation: 0.693412
cta: {}
layout_spectrum: 1
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
