name: DoSell
favicon: null
layout_spectrum: 0.16516
typography_spectrum: 0.56769
title: 'DoSell Blog: News, Trends, Insights of Business Architecture, Engineering & Innovation'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#005d51'
    - '#25b9b9'
    - '#ba421f'
    - '#740005'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
