analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B0C0C8'
    - '#3080A0'
    - '#888070'
    - '#40B0D0'
    - '#D06858'
  brandStrength: 0.849662
  lightness: 0.924831
  rhythmicContrast: 0.738176
  saturation: 0.693412
cta: {}
layout_spectrum: 0.483953
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
