analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E8F0E8'
    - '#000000'
    - '#808880'
    - '#000000'
    - '#000000'
  brandStrength: 0.714527
  lightness: 0.919764
  rhythmicContrast: 0.403716
  saturation: 0.552365
cta: {}
layout_spectrum: 0.465372
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
