name: LabShare Engineering Blog
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc37d846-eaeb-4af4-afad-834ce619a0ec.png
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2642fcfd-e58d-414d-a380-36bc1ac340a2.png
layout_spectrum: 0.17987976768035627
typography_spectrum: 0.24667427840070927
cta: {}
analytics:
  google: UA-71835463-1
opengraph:
  type: ''
  appId: ''
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/4f317b41-c1ce-4230-b0c1-8fffedc43688.jpg
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.8693458878305178
  lightness: 0.17508673953832968
  saturation: 0.9390946164466256
  rhythmicContrast: 0.6854460190222738
purpose:
  - type: contact
    label: Contact me
    url: 'mailto:tibor.zahorecz@dosell.io'
  - type: external
    label: Software Security Experts
    url: 'https://www.labsharegroup.com/'
title: LabShare Engineering Blog
description: 'Engineering, Software Security, Software Development'
author:
  name: Tibor Zahorecz
  url: 'http://www.labsharegroup.com/'
  email: tibor.zahorecz@dosell.io
content_rating:
  adult: false
navigation:
  - name: Software Security Experts
    url: 'https://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FuFM4DaUotwg%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DuFM4DaUotwg&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FuFM4DaUotwg%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      '@type': VideoObject
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=uFM4DaUotwg'
      inLanguage: en
      keywords:
        - dosell
        - labshare
        - duration
        - views
        - sectio
        - service
        - engineering
        - build
        - '105'
        - venture
      title: DoSell short
      publisher:
        name: YouTube
        domain: www.youtube.com
        url: 'https://www.youtube.com/'
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
      author:
        - name: DoSell
          url: 'https://www.youtube.com/channel/UCMSQTFDkisNiUKcI78zmZ5A'
          avatar: {}
      starred: false
      description: introduction
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
