name: DoSell
favicon: null
layout_spectrum: 0.50561
typography_spectrum: 0.666385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#252e37'
    - '#bababa'
    - '#666d73'
    - '#d12249'
  brandStrength: 0.8125
  lightness: 0.919764
  saturation: 0.552365
  rhythmicContrast: 0.403716
purpose: []
