analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#F0F0E8'
    - '#721713'
    - '#808080'
    - '#E04840'
    - '#000000'
  brandStrength: 0.866554
  lightness: 0.945946
  rhythmicContrast: 0.646959
  saturation: 0.576858
cta: {}
layout_spectrum: 0.467061
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
