typography_spectrum: 0.37233693548478186
color:
  brandColors:
    - '#AFA59B'
    - '#FFFFFF'
    - '#37342D'
    - '#000000'
    - '#8C0000'
  brandStrength: 0.29457573569379747
  lightness: 0.2161838235333562
  saturation: 0.6489539965987206
  rhythmicContrast: 0.46642489614896476
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6901410014834255
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
name: 'DoSell Open Innovation Blog '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
  - name: Business Architecture
    url: 'http://www.buildventure.net/'
    type: external
favicon: null
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
purpose: []
