analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#185070'
    - '#587890'
    - '#4090B0'
    - '#E8F8F0'
  brandStrength: 0.763514
  lightness: 0.921453
  rhythmicContrast: 0.616554
  saturation: 0.750845
cta: {}
layout_spectrum: 0.467905
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
