analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.866554
  lightness: 0.945946
  rhythmicContrast: 0.646959
  saturation: 0.576858
cta: {}
layout_spectrum: 0.467061
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
