analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#185070'
    - '#587890'
    - '#4090B0'
    - '#E8F8F0'
  brandStrength: 0.866554
  lightness: 0.804054
  rhythmicContrast: 0.646959
  saturation: 0.576858
cta: {}
layout_spectrum: 0.467905
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
