analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.674831
  lightness: 0.6875
  rhythmicContrast: 0.5
  saturation: 0.75
cta: {}
layout_spectrum: 0.47371
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
