analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#6f7f8e'
    - '#2e2b26'
    - '#d9d9d9'
    - '#020202'
    - '#ba957b'
  brandStrength: 0.875845
  lightness: 0.921453
  rhythmicContrast: 0.616554
  saturation: 0.750845
cta: {}
layout_spectrum: 0.524493
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
