name: DoSell
favicon: null
layout_spectrum: 0.95578
typography_spectrum: 0.8222
title: DoSell Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#727469'
    - '#2d3027'
    - '#f05d63'
    - '#ead443'
  brandStrength: 0.3125
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
