name: DoSell
favicon: null
layout_spectrum: 0.7305302498862147
typography_spectrum: 0.1800719159655273
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6039759228006005
  lightness: 0.45594477793201804
  saturation: 0.4251121545676142
  rhythmicContrast: 0.1596645973622799
purpose: []
