name: DoSell
favicon: null
layout_spectrum: 0.467061
typography_spectrum: 0.666385
title: 'DoSell: News, Trends, Insights of Product Design - Engineering - Business Architecture'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F0F0E8'
    - '#721713'
    - '#808080'
    - '#E04840'
    - '#000000'
  brandStrength: 0.866554
  lightness: 0.945946
  saturation: 0.576858
  rhythmicContrast: 0.646959
purpose: []
