analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E0E0E0'
    - '#000000'
    - '#98A098'
    - '#000000'
    - '#000000'
  brandStrength: 0.559966
  lightness: 0.893581
  rhythmicContrast: 0.701858
  saturation: 0.624155
cta: {}
layout_spectrum: 0.384291
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
