typography_spectrum: 0.460304
color:
  brandColors:
    - '#E8E8E0'
    - '#000000'
    - '#788078'
    - '#000000'
    - '#000000'
  brandStrength: 0.6875
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.121622
analytics:
  google: UA-71835463-1
  facebook: null
  twitter: null
name: 'DoSell Open Innovation Blog '
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Open Innovation Platform
    url: 'http://www.labsharegroup.com/'
    type: external
favicon: null
title: 'News, Trends, Insights of Engineering, IoT, software security ...'
purpose: []
