analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#E8E8E0'
    - '#5D4B28'
    - '#808080'
    - '#C8B080'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.912162
  rhythmicContrast: 0.5
  saturation: 0.8125
cta: {}
layout_spectrum: 0.10689
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.67652
