analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#A8B8B8'
    - '#282010'
    - '#909080'
    - '#B69249'
    - '#000000'
  brandStrength: 0.875
  lightness: 0.830236
  rhythmicContrast: 0.701858
  saturation: 0.6875
cta: {}
layout_spectrum: 0.461149
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
