analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B8C0B8'
    - '#987010'
    - '#909898'
    - '#D8A808'
    - '#000000'
  brandStrength: 0.779561
  lightness: 0.79223
  rhythmicContrast: 0.701858
  saturation: 0.624155
cta: {}
layout_spectrum: 0.485642
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
