analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B0B0B8'
    - '#000000'
    - '#808888'
    - '#000000'
    - '#000000'
  brandStrength: 0.6875
  lightness: 0.75
  rhythmicContrast: 0.25
  saturation: 0.625
cta: {}
layout_spectrum: 0.113176
name: 'DoSell Blog '
opengraph: {}
purpose: []
typography_spectrum: 0.460304
