analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#B8B8B8'
    - '#000000'
    - '#787878'
    - '#000000'
    - '#F0F8E8'
  brandStrength: 0.655405
  lightness: 0.864865
  rhythmicContrast: 0.701858
  saturation: 0.753378
cta: {}
layout_spectrum: 0.449324
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
