analytics:
  google: UA-71835463-1
color:
  brandColors:
    - '#D0C8A8'
    - '#786830'
    - '#A89860'
    - '#C0A870'
    - '#000000'
  brandStrength: 0.540541
  lightness: 0.820101
  rhythmicContrast: 0.641892
  saturation: 0.682432
cta: {}
layout_spectrum: 0.423986
name: DoSell
opengraph: {}
purpose: []
typography_spectrum: 0.666385
